change default port from 8080 to 9931

diff --git a/modules/zsh/functions b/modules/zsh/functions
--- a/modules/zsh/functions
+++ b/modules/zsh/functions
@@ -2,41 +2,44 @@
 
 # Create a new directory and enter it
 function mkcd() {
-	# Check if no arguments are provided
-	if [[ -z "$1" ]]; then
-		printf 'Usage: mkcd <directory_name>\n'
-		printf 'Error: No directory name provided.\n'
+	local -r target_dir="$1"
+	local -r msg="Usage: mkcd <directory_name>"
+
+	if [[ -z "${target_dir}" ]]; then
+		printf '%s\n' "${msg}" >&2
+		printf 'Error: No directory name provided.\n' >&2
 		return 1
 	fi
 
-	# Check if more than one argument is provided
-	if [[ "$" -gt 1 ]]; then
-		printf 'Usage: mkcd <directory_name>\n'
-		printf 'Error: Too many arguments. Please provide only one directory name.\n'
+	if [[ "${target_dir}" -gt 1 ]]; then
+		printf '%s\n' "${msg}" >&2
+		printf 'Error: Too many arguments. Please provide only one directory name.\n' >&2
 		return 1
 	fi
-
-	local target_dir="$1"
 
 	# Check if the directory already exists
-	if [[ -d "$target_dir" ]]; then
+	if [[ -d "${target_dir}" ]]; then
 		printf 'Directory %s already exists. Changing into it.\n' "${target_dir}"
-		if cd "$target_dir"; then
+		if cd "${target_dir}"; then
 			printf 'Successfully changed to: %s\n' "$(pwd)"
 			return 0
 		else
-			printf 'Error: Could not change to directory %s\n' "${target_dir}"
+			printf 'Error: Could not change to directory %s\n' "${target_dir}" >&2
 			return 1
 		fi
 	fi
 
 	# Attempt to create the directory and then change into it
-	if mkdir -p "$target_dir" && cd "$target_dir"; then
-		printf 'Successfully created and changed to: %s\n' "$(pwd)"
-	else
-		printf 'Error: Could not create or change to directory %s.\n' "${target_dir}"
+	if ! command mkdir -p "${target_dir}" 2>/dev/null; then
+		printf 'Error: Could not create directory %s.\n' "${target_dir}" >&2
 		return 1
 	fi
+	if ! command cd "${target_dir}" 2>/dev/null; then
+		printf 'Error: Could not change to directory %s.\n' "${target_dir}" >&2
+		return 1
+	fi
+	printf 'Successfully created and changed to: %s\n' "$(pwd)"
+	return 0
 }
 
 # Internal helper function to prompt for email and generate the key
